//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beans.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beans.API.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin users cannot be {0}..
        /// </summary>
        internal static string AdminUsers {
            get {
                return ResourceManager.GetString("AdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters, expected positive word and digit counts, found &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string BadGenerate {
            get {
                return ResourceManager.GetString("BadGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;buy&apos; or &apos;sell&apos;, found &apos;{0}&apos;..
        /// </summary>
        internal static string BuySell {
            get {
                return ResourceManager.GetString("BuySell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user cannot be deleted. It has associated data which must be deleted first..
        /// </summary>
        internal static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Context not found..
        /// </summary>
        internal static string ContextNotFound {
            get {
                return ResourceManager.GetString("ContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number greater than zero..
        /// </summary>
        internal static string GTZero {
            get {
                return ResourceManager.GetString("GTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model passed is invalid. It is either null or is missing required information..
        /// </summary>
        internal static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} with the {1} &apos;{2}&apos; was found..
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Loan Amount cannot be larget than the Maximum Loan Balance..
        /// </summary>
        internal static string MLAGreater {
            get {
                return ResourceManager.GetString("MLAGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If exchange loans are permitted, then the Maximum Loan Amount must be non-zero..
        /// </summary>
        internal static string MLANonZero {
            get {
                return ResourceManager.GetString("MLANonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history was found for that bean and date range..
        /// </summary>
        internal static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated. Please log in..
        /// </summary>
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view that content or perform that action..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} with the {1} &apos;{2}&apos; was found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User create returned a success status, but the user was not found after using the email address &apos;{0}&apos;..
        /// </summary>
        internal static string UserNotFoundAfterCreate {
            get {
                return ResourceManager.GetString("UserNotFoundAfterCreate", resourceCulture);
            }
        }
    }
}
